server:
  port:  8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patientrecord
    username: dev_user
    password: w0a5nhnu4
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true
  #image
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

logging:
  file:
    name: log/patientrecord.log
  pattern:
    file: "%d %-5level [%thread]  %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[org.patientrecord]': DEBUG

management: #actuator
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled:  true

  gamingpromarket:
    app:
      jwtSecret: LCPatientRecord2023
      jwtExpirationMS: 86400000

info:
  application:
    name: 'Life Center Patient Record System Backend App'
    description: 'This is Life Center Patient Record System Backend Project'
    version: '@project.version@'


